### ISSUE TITLE
h1, h2, ... styling?

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-proxy#10]
@kellrott, @prismofeverything 
Think this is part of hugo theme?... 
![image](https://cloud.githubusercontent.com/assets/47808/26185629/ff245e78-3b40-11e7-8f01-b79e482d15e9.png)

**Comment by kellrott** [comment]
That may be the result of the markdown processing engine hugo uses.
That page should be rendered by https://github.com/bmeg/bmeg-proxy/blob/dev/themes/bmeg/layouts/_default/single.html The `.Content` block is the result of the template engine.
