### ISSUE TITLE
bmeg proxy python should be async ?

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-proxy#17]
"
Tornado uses a single-threaded event loop. This means that all application code should aim to be asynchronous and non-blocking because only one operation can be active at a time.
"

See
https://github.com/bmeg/bmeg-proxy/blob/master/proxy.py#L45-L47
vs.
http://www.tornadoweb.org/en/stable/guide/async.html#examples

@prismofeverything

**Comment by prismofeverything** [comment]
Looks like your latest pull request resolved this, thanks Brian!
