### ISSUE TITLE
Add redux to manage state, then encode state in URL

### ISSUE THREAD

**Issue by prismofeverything** [bmeg/bmeg-proxy#22]
We need a way to create links that lead back to a fully populated view.

The proposal is twofold:

* Add redux to manage the state of the application
* Encode this state into the URL so that visiting it restores the state of the current view.

**Comment by bwalsh** [comment]
@prismofeverything  Hey Ryan - depending on where you are with this and your other dependencies, I'd be glad to pitch in on this one when I get back on Monday
